services:
  postgresql:
    container_name: ai-based-project-allocation-postgresql
    image: postgres:latest 
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai-based-project-allocation
    ports:
     - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  flask:
    container_name: ai-based-project-allocation-flask
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:  
      - "5000:5000"
    depends_on:
      - postgresql
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_NAME=ai-based-project-allocation
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgresql:5432/ai-based-project-allocation
    volumes:
      - ./backend:/app
    command: ["sh", "-c", "while ! timeout 1 bash -c 'cat < /dev/null > /dev/tcp/postgresql/5432'; do sleep 1; done; flask run --host=0.0.0.0"]
  
  vuejs:
    container_name: ai-based-project-allocation-vuejs
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:  
      - "8080:8080"
    depends_on:
      - flask
    


volumes: 
  data:
